server {
    listen 80;

    # Route PostgREST sous /rest/v1/ comme Supabase
    location /rest/v1/ {
        proxy_pass http://rest:3000/;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Accept-Profile $http_accept_profile;
        proxy_set_header Content-Profile $http_content_profile;
        proxy_set_header Prefer $http_prefer;
    }
}
